export { Login as ScreenLogin } from "./LoginPage";
export { Cadastro as ScreenCadastro} from "./CadastrarPage";
export { Home as ScreenHome } from "./Home";
export { EditarDesabafo as ScreenEditDesabafo} from "./EditDesabafoPage";
export { Ansiedade as ScreenAnsiedade } from "./AnsiedadePage";
export { Estresse as ScreenEstresse } from "./EstressePage";
export { Desabafo as ScreenDesabafo } from "./DesabafoPage";
export { SCamera as ScreenCamera} from "./CameraPage";
export { SPhoto as ScreenPhoto } from "./PhotoPage";
export { SLocation as ScreenLocation} from "./LocationPage";
export { Calendario as ScreenCalendar } from "./CalendarPage";
export { Acelerometro as ScreenCarro} from "./Acelerometro";
export { Metas as ScreenMetas } from "./MetasPage";
export { AddMeta as ScreenAddMeta } from "./AddMetaPage";
export { EditMeta as ScreenEditMeta } from "./EditMetaPage";
export { Perfil as ScreenPerfil} from "./ProfilePage";
export { EditarPerfil as ScreenEditProfile } from "./EditProfilePage";